In [1]:
import torch
import numpy as np

In [ ]:
创建一个5*3的未初始化的Tensor

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


创建一个随机初始化的Tensor

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8925, 0.9359, 0.9049],
        [0.1119, 0.4970, 0.9760],
        [0.2339, 0.7160, 0.7503],
        [0.4053, 0.1945, 0.4315],
        [0.3776, 0.8401, 0.8990]])


创建一个5*3的long型全0的Tensor

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)

In [5]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

根据数据创建

In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


通过现有的Tensor来创建

In [7]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-1.2452,  0.1009, -0.1142],
        [ 0.6704, -1.5655, -2.4288],
        [-0.1965, -0.8538, -0.5346],
        [ 0.0907, -1.4658, -0.1983],
        [ 0.6809, -1.4911,  0.2137]])


获取tensor的形状

In [9]:
print(x.shape)

torch.Size([5, 3])


In [10]:
print(x.size())

torch.Size([5, 3])


算术操作

In [12]:
print(x)

tensor([[-1.2452,  0.1009, -0.1142],
        [ 0.6704, -1.5655, -2.4288],
        [-0.1965, -0.8538, -0.5346],
        [ 0.0907, -1.4658, -0.1983],
        [ 0.6809, -1.4911,  0.2137]])


In [16]:
y = torch.rand(5, 3)
y

tensor([[0.8931, 0.8735, 0.6159],
        [0.2919, 0.5293, 0.7160],
        [0.8661, 0.2199, 0.8450],
        [0.7603, 0.6514, 0.5286],
        [0.9609, 0.4459, 0.4613]])

In [13]:
print(x + y)

tensor([[-1.2069,  1.0099,  0.2934],
        [ 0.9308, -0.6595, -1.8116],
        [ 0.1392, -0.6129, -0.0184],
        [ 0.3349, -0.6359,  0.4721],
        [ 0.9910, -1.3970,  1.1402]])


In [29]:
a = torch.arange(16).reshape((4, 4)).float()
a

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [34]:
b = torch.rand((4, 4))
b

tensor([[0.1721, 0.3401, 0.2587, 0.6583],
        [0.9001, 0.4919, 0.2662, 0.4547],
        [0.6030, 0.6147, 0.7247, 0.3342],
        [0.4255, 0.5154, 0.9083, 0.0807]])

In [35]:
print(torch.add(a, b))

tensor([[ 0.1721,  1.3401,  2.2587,  3.6583],
        [ 4.9001,  5.4919,  6.2662,  7.4547],
        [ 8.6030,  9.6147, 10.7247, 11.3342],
        [12.4255, 13.5154, 14.9083, 15.0807]])


很明显可以看出相应的元素相加

相加可以指定输出

In [36]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[-0.3522,  0.9743,  0.5017],
        [ 0.9622, -1.0362, -1.7128],
        [ 0.6696, -0.6340,  0.3103],
        [ 0.8510, -0.8145,  0.3302],
        [ 1.6419, -1.0451,  0.6750]])

In [37]:
torch.add(x, y, out=resul)

NameError: name 'resul' is not defined

这里得注意，指定得输出必须已经定义好了

将x加到y，该表y的值。

In [39]:
y.add_(x)

tensor([[-0.3522,  0.9743,  0.5017],
        [ 0.9622, -1.0362, -1.7128],
        [ 0.6696, -0.6340,  0.3103],
        [ 0.8510, -0.8145,  0.3302],
        [ 1.6419, -1.0451,  0.6750]])

In [43]:
a

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [41]:
c = a[0, :]

In [42]:
c

tensor([0., 1., 2., 3.])

In [46]:
d = a.view(16)
d

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.])

In [48]:
d = a.view(-1, 8)
d

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])

In [49]:
a_cp = a.clone().view(16)
a_cp

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.])

In [50]:
a_cp[0]=3
a_cp

tensor([ 3.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.])

In [51]:
a

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [52]:
d

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])

In [53]:
d[0][0]=3

In [54]:
d

tensor([[ 3.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])

In [55]:
a

tensor([[ 3.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [56]:
x = torch.randn(1)

In [57]:
x

tensor([0.3405])

In [58]:
print(x.item())

0.34053659439086914


In [63]:
x = torch.arange(1, 5).view(1, 4)

In [64]:
x

tensor([[1, 2, 3, 4]])

In [65]:
y = torch.arange(1, 4).view(3, 1)
y

tensor([[1],
        [2],
        [3]])

In [66]:
print(x+y)

tensor([[2, 3, 4, 5],
        [3, 4, 5, 6],
        [4, 5, 6, 7]])


In [67]:
y = torch.arange(1, 4)

In [68]:
y

tensor([1, 2, 3])

In [69]:
x

tensor([[1, 2, 3, 4]])

In [70]:
print(x+y)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

运算的内存开销

In [2]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])

In [3]:
id_before = id(y)

In [4]:
id_before

2412339276248

像下列的运算，会新开辟一个内存，然后将y指向新的内存

In [5]:
y = y + x

In [6]:
id(y) == id_before

False

In [7]:
y

tensor([4, 6])

In [8]:
id(y)

2412339274520

如果想指定结果到原来得内存，下列操作

In [9]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x

In [10]:
print(id(y) == id_before)

True


该操作也可以通过add_()达到相同得效果

In [11]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y)
print(id(y) == id_before)

True


# tensor和numpy得相互转换

tensor转numpy
使用numpy()将Tensor转换成numpy数组

In [16]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [17]:
a += 1 
print(a, b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [18]:
b += 1
print(a, b)

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


numpy数组转Tensor

In [20]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [21]:
a += 1
print(a, b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [22]:
b += 1
print(a, b)

[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


注意，这个方法将numpy数组进行拷贝，返回的Tensor与源numpy数组不共享内存

In [23]:
c = torch.tensor(a)
c

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)

In [24]:
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


Tensor ON GPU

In [26]:
x

tensor([1, 2])

In [29]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建一个Tensor
    x = x.to(device)  # 等价于.to("cuda")
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))  # to()还可以同时改变数据类型

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)


In [30]:
x

tensor([1, 2], device='cuda:0')

In [31]:
y

tensor([1, 1], device='cuda:0')

In [32]:
z

tensor([2, 3], device='cuda:0')

In [33]:
z.dtype

torch.int64